include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_types_as_parameter_names: true
    avoid_web_libraries_in_flutter: true
