/// 100+ pre-built agent tasks — schedule or run on demand
/// Each task is a self-contained operation the agent can execute
class AgentTaskLibrary {
  static const Map<String, Map<String, String>> tasks = {
    // === DAILY (25 tasks) ===
    "daily_standup": {"desc": "Generate daily standup from git history", "tool": "daily_standup"},
    "daily_commit_summary": {"desc": "Summarize today's commits with emoji categories", "tool": "git_sync"},
    "daily_code_review": {"desc": "Review all code changed today", "tool": "self_review"},
    "daily_test_check": {"desc": "Run test suite and report failures", "tool": "run_command"},
    "daily_lint_check": {"desc": "Run linter and report warnings", "tool": "run_command"},
    "daily_type_check": {"desc": "Run typecheck and report errors", "tool": "run_command"},
    "daily_build_check": {"desc": "Run build and verify it succeeds", "tool": "run_command"},
    "daily_dependency_audit": {"desc": "npm audit / pip-audit for vulnerabilities", "tool": "run_command"},
    "daily_log_check": {"desc": "Check error logs for new patterns", "tool": "run_command"},
    "daily_backup_reminder": {"desc": "Remind to backup database", "tool": "ask_user"},
    "daily_pr_review": {"desc": "Check for open PRs needing review", "tool": "github_list_prs"},
    "daily_issue_triage": {"desc": "Triage new GitHub issues", "tool": "github_list_issues"},
    "daily_disk_check": {"desc": "Check disk usage in project", "tool": "check_bundle_size"},
    "daily_git_cleanup": {"desc": "Check for stale branches to delete", "tool": "git_branch"},
    "daily_env_check": {"desc": "Verify .env.example matches actual usage", "tool": "generate_env_example"},
    "daily_todo_scan": {"desc": "Find TODO/FIXME comments added today", "tool": "search_code"},
    "daily_security_scan": {"desc": "Quick security check on changed files", "tool": "self_review"},
    "daily_performance_check": {"desc": "Check changed files for perf issues", "tool": "profile_performance"},
    "daily_doc_check": {"desc": "Verify README is up to date", "tool": "read_file"},
    "daily_coverage_check": {"desc": "Check test coverage trends", "tool": "test_coverage"},
    "daily_metric_report": {"desc": "Report: commits, files changed, lines added/removed", "tool": "code_stats"},
    "daily_bundle_check": {"desc": "Check bundle size hasn't grown unexpectedly", "tool": "check_bundle_size"},
    "daily_api_test": {"desc": "Smoke test critical API endpoints", "tool": "api_test"},
    "daily_ssl_check": {"desc": "Check SSL certificate expiry dates", "tool": "ssl_check"},
    "daily_uptime_check": {"desc": "Ping production and staging servers", "tool": "network_ping"},

    // === WEEKLY (25 tasks) ===
    "weekly_dependency_update": {"desc": "Check for outdated dependencies", "tool": "check_deps"},
    "weekly_security_full": {"desc": "Full OWASP security scan of project", "tool": "security_scan"},
    "weekly_performance_full": {"desc": "Full performance profile of project", "tool": "profile_performance"},
    "weekly_dead_code": {"desc": "Find and report dead code", "tool": "dead_code"},
    "weekly_circular_deps": {"desc": "Check for circular dependencies", "tool": "circular_deps"},
    "weekly_complexity_report": {"desc": "Cyclomatic complexity per file", "tool": "complexity_report"},
    "weekly_duplicate_code": {"desc": "Find duplicate code blocks", "tool": "find_duplicates"},
    "weekly_code_stats": {"desc": "Full code statistics report", "tool": "code_stats"},
    "weekly_changelog_draft": {"desc": "Draft CHANGELOG.md from week's commits", "tool": "generate_changelog"},
    "weekly_refactor_targets": {"desc": "Identify files needing refactoring", "tool": "lsp_analyze"},
    "weekly_test_gaps": {"desc": "Find untested code paths", "tool": "suggest_tests"},
    "weekly_doc_health": {"desc": "Check all docs are current", "tool": "read_file"},
    "weekly_env_audit": {"desc": "Audit all env vars and secrets", "tool": "generate_env_example"},
    "weekly_branch_cleanup": {"desc": "Delete merged branches", "tool": "git_branch"},
    "weekly_release_check": {"desc": "Check if release is ready", "tool": "check_deploy_readiness"},
    "weekly_backup_verify": {"desc": "Verify latest backup is restorable", "tool": "run_command"},
    "weekly_log_rotate": {"desc": "Check log sizes, suggest rotation", "tool": "run_command"},
    "weekly_db_optimize": {"desc": "Check for missing indexes, slow queries", "tool": "index_suggestion"},
    "weekly_i18n_check": {"desc": "Find un-internationalized strings", "tool": "i18n_find"},
    "weekly_a11y_check": {"desc": "Accessibility audit of UI code", "tool": "accessibility_audit"},
    "weekly_bundle_analyze": {"desc": "Analyze bundle for size optimizations", "tool": "check_bundle_size"},
    "weekly_version_bump": {"desc": "Suggest version bump based on changes", "tool": "semver_bump"},
    "weekly_contributor_stats": {"desc": "Show contributor activity for the week", "tool": "git_blame"},
    "weekly_retrospective": {"desc": "Generate weekly retrospective from commits", "tool": "daily_standup"},
    "weekly_competitor_check": {"desc": "Check competitor GitHub repos for updates", "tool": "web_search"},

    // === ON PUSH / PRE-COMMIT (15 tasks) ===
    "precommit_lint": {"desc": "Lint staged files before commit", "tool": "run_command"},
    "precommit_format": {"desc": "Format staged files", "tool": "format_code"},
    "precommit_typecheck": {"desc": "Typecheck before commit", "tool": "run_command"},
    "precommit_test": {"desc": "Run affected tests before commit", "tool": "run_command"},
    "precommit_self_review": {"desc": "Self-review changes before commit", "tool": "self_review"},
    "precommit_secret_scan": {"desc": "Scan for accidentally committed secrets", "tool": "security_scan"},
    "precommit_import_check": {"desc": "Verify imports are valid", "tool": "check_imports"},
    "precommit_diff_preview": {"desc": "Show diff of what will be committed", "tool": "diff_preview"},
    "postcommit_push": {"desc": "Push after commit", "tool": "git_sync"},
    "postcommit_create_pr": {"desc": "Create PR if committing to feature branch", "tool": "create_pr"},
    "postcommit_notify": {"desc": "Notify team about new commit", "tool": "ask_user"},
    "prepush_test_full": {"desc": "Run full test suite before push", "tool": "run_command"},
    "prepush_conflict_check": {"desc": "Check for potential merge conflicts", "tool": "detect_conflicts"},
    "prepush_build": {"desc": "Verify build succeeds before push", "tool": "run_command"},
    "prepush_changelog": {"desc": "Update changelog before pushing release", "tool": "generate_changelog"},

    // === ON DEPLOY (10 tasks) ===
    "deploy_check_readiness": {"desc": "Check deployment readiness", "tool": "check_deploy_readiness"},
    "deploy_health_check": {"desc": "Health check after deploy", "tool": "api_test"},
    "deploy_rollback_plan": {"desc": "Prepare rollback plan", "tool": "ask_user"},
    "deploy_smoke_test": {"desc": "Run smoke tests after deploy", "tool": "api_test"},
    "deploy_monitor_errors": {"desc": "Monitor error rate for 5 min after deploy", "tool": "run_command"},
    "deploy_ssl_verify": {"desc": "Verify SSL after deploy", "tool": "ssl_check"},
    "deploy_dns_verify": {"desc": "Verify DNS propagation", "tool": "dns_lookup"},
    "deploy_cache_clear": {"desc": "Clear CDN/application cache", "tool": "run_command"},
    "deploy_db_migrate": {"desc": "Run database migrations", "tool": "run_command"},
    "deploy_notify": {"desc": "Notify team deployment complete", "tool": "ask_user"},

    // === MAINTAIN (15 tasks) ===
    "maintain_update_deps": {"desc": "Update all dependencies to latest compatible", "tool": "check_deps"},
    "maintain_audit_fix": {"desc": "Auto-fix security vulnerabilities", "tool": "run_command"},
    "maintain_clean_build": {"desc": "Clean build artifacts", "tool": "run_command"},
    "maintain_validate_configs": {"desc": "Validate all JSON/YAML configs", "tool": "validate_config"},
    "maintain_check_licenses": {"desc": "Audit dependency licenses", "tool": "generate_license"},
    "maintain_update_docs": {"desc": "Update API docs from code changes", "tool": "generate_api_docs"},
    "maintain_optimize_images": {"desc": "Compress all project images", "tool": "image_optimize"},
    "maintain_archive_old": {"desc": "Archive old branches/logs", "tool": "archive_create"},
    "maintain_benchmark": {"desc": "Run performance benchmarks", "tool": "run_command"},
    "maintain_analyze_bundle": {"desc": "Analyze and suggest bundle optimizations", "tool": "check_bundle_size"},
    "maintain_seed_refresh": {"desc": "Refresh seed data from production sample", "tool": "seed_data_gen"},
    "maintain_schema_validate": {"desc": "Validate DB schema matches code models", "tool": "sql_schema"},
    "maintain_cache_warm": {"desc": "Warm application cache", "tool": "run_command"},
    "maintain_log_rotate": {"desc": "Rotate and compress logs", "tool": "archive_create"},
    "maintain_health_report": {"desc": "Generate project health report", "tool": "code_stats"},

    // === IDEAS & CREATIVITY (10 tasks) ===
    "ideas_feature_brainstorm": {"desc": "Brainstorm 10 feature ideas using 80 techniques", "tool": "delegate_task"},
    "ideas_architecture_review": {"desc": "Review architecture for improvements", "tool": "delegate_task"},
    "ideas_ux_improvements": {"desc": "Suggest UX improvements from user perspective", "tool": "delegate_task"},
    "ideas_monetization": {"desc": "Brainstorm monetization strategies", "tool": "delegate_task"},
    "ideas_growth_hacks": {"desc": "Suggest growth hacking strategies", "tool": "delegate_task"},
    "ideas_tech_debt_paydown": {"desc": "Prioritize tech debt items", "tool": "create_plan"},
    "ideas_competitor_analysis": {"desc": "Research competitor features", "tool": "web_search"},
    "ideas_user_persona": {"desc": "Generate user personas for testing", "tool": "generate_mock"},
    "ideas_ab_test": {"desc": "Design A/B test for a feature", "tool": "delegate_task"},
    "ideas_roadmap": {"desc": "Generate product roadmap from issues/commits", "tool": "create_plan"},
  };
}
